single : 
	pdflatex Spectral_circ.tex

full :
	pdflatex Spectral_circ.tex
	bibtex Spectral_circ.aux
	pdflatex Spectral_circ.tex
	pdflatex Spectral_circ.tex

clean :
	rm Spectral_circ.aux Spectral_circ.bbl Spectral_circ.blg Spectral_circ.spl Spectral_circ.log Spectral_circ.out
	rm Bibliography.log
