all : 
	pdflatex Spectral_circ.tex
	bibtex Spectral_circ.aux
	pdflatex Spectral_circ.tex
	pdflatex Spectral_circ.tex

clean :
	rm Spectral_circ.aux
	rm Spectral_circ.bbl
	rm Spectral_circ.blg
	rm Spectral_circ.log
	rm Spectral_circ.out
	rm Bibliography.log
